# Generated by Django 3.2.3 on 2021-05-23 17:08

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('content', models.FileField(default='-', upload_to='')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField(auto_now_add=True)),
                ('subject_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
                ('state', models.BooleanField()),
                ('subject_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=1450)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('teacher_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=30)),
                ('password', models.CharField(default='-', max_length=254, validators=[django.contrib.auth.password_validation.CommonPasswordValidator])),
                ('email', models.EmailField(default='-', max_length=50)),
                ('course_id', models.IntegerField(default=-1)),
                ('acc_type', models.IntegerField(default=0)),
            ],
        ),
    ]
