# Generated by Django 3.2.3 on 2021-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='content',
            field=models.FileField(default=' ', upload_to=''),
        ),
    ]
